name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m nltk.downloader punkt

    - name: Download NLTK data (stopwords)
      run: |
        python -c "import nltk; nltk.download('stopwords')"

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: List files
      run: ls -R

    - name: Start API
      run: python Application/api.py &

    - name: Start Streamlit app
      run: streamlit run Application/app.py &

    - name: Wait for services to be ready
      run: sleep 30

    - name: Run tests
      run: |
        python -m pytest TestsUnitaires/

    - name: Deploiement sur Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
