name: Déploiement sur Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest selenium webdriver-manager
        python -m nltk.downloader punkt stopwords

    - name: Install Microsoft Edge and WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        sudo apt-get install -y microsoft-edge-webdriver
        echo "Edge et WebDriver installés avec succès !"

    - name: Verify Edge and WebDriver installation
      run: |
        edge_version=$(microsoft-edge --version)
        webdriver_version=$(msedgedriver --version || echo "WebDriver not found")
        echo "Edge version: $edge_version"
        echo "WebDriver version: $webdriver_version"

    - name: Start API
      run: |
        nohup python TestsUnitaires/api.py > api.log 2>&1 &

    - name: Start Streamlit app
      run: |
        nohup streamlit run TestsUnitaires/app.py > streamlit.log 2>&1 &

    - name: Wait for services to be ready
      run: |
        sleep 5
        nc -zv localhost 8501  # Vérifie que Streamlit tourne
        nc -zv localhost 5000  # Vérifie que l'API tourne

    - name: Run tests (unit + Selenium)
      env:
        DISPLAY: ":99"  # Nécessaire pour Selenium en mode headless
      run: |
        pytest TestsUnitaires/

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
