name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install webdriver-manager
        python -m nltk.downloader punkt
        python -m nltk.downloader stopwords
        python -m nltk.downloader punkt_tab

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Start API
      run: python Application/api.py &

    - name: Start Streamlit app
      run: streamlit run Application/app.py &

    - name: Wait for services to be ready
      run: sleep 30 

    - name: Verify API is running
      run: |
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:57077

    - name: Verify Streamlit app is running
      run: |
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8501

    - name: Run tests
      run: |
        python -m pytest TestsUnitaires/

    - name: Deploiement sur Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
