on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m nltk.downloader punkt

    - name: Download NLTK data (stopwords)
      run: |
        python -c "import nltk; nltk.download('stopwords')"

    - name: Set up Microsoft Edge
      uses: browser-actions/setup-edge@latest
      with:
        edge-version: 'latest'

    - name: Download msedgedriver
      run: |
        wget https://msedgedriver.azureedge.net/<version>/edgedriver_linux64.zip -O msedgedriver.zip
        unzip msedgedriver.zip
        chmod +x msedgedriver

    - name: Verify msedgedriver permissions
      run: ls -l msedgedriver

    - name: Display Edge version
      run: edge --version

    - name: Display msedgedriver version
      run: ./msedgedriver --version

    - name: Start API
      run: python TestsUnitaires/api.py &

    - name: Start Streamlit app
      run: streamlit run TestsUnitaires/app.py &

    - name: Wait for services to be ready
      run: sleep 30

    - name: Run tests
      run: |
        python -m pytest TestsUnitaires/

    - name: Deploiement sur Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
